tagFormat: app-v${version}
branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: fix(app)
          release: patch
        - type: feat(app)
          release: minor
        - type: feat(app)!
          release: major
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - "@google/semantic-release-replace-plugin"