tagFormat: app-v${version}
preset: conventionalcommits
plugins:
  - "@semantic-release/github"

  - - "@semantic-release/commit-analyzer"
    - releaseRules:
      - type: fix-app
        release: patch        
      - type: feat-app
        release: minor
      - type: feat-app!
        release: major

  - "@semantic-release/release-notes-generator"
  
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files: "deployment/helm-chart/Chart.yaml"
          allowEmptyPaths: false
          disableGlobs: false
          from: "^appVersion: .*"
          to: "appVersion: ${nextRelease.version}"

  - - "@semantic-release/git"
    - message: "bump app version: ${nextRelease.version}"
      assets:
        - "deployment/helm-chart/Chart.yaml"