tagFormat: app-v${version}

plugins:
  - "@semantic-release/github"

  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits 
      releaseRules:
        - type: fix-app
          release: patch        
        - type: feat-app
          release: minor
        - type: feat-app!
          release: major
      presetConfig:
        types:
          - type: fix-app
            section: Bug Fixes
          - type: feat-app
            section: Features          

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits 

  
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files: "deployment/helm-chart/Chart.yaml"
          allowEmptyPaths: false
          disableGlobs: false
          from: "^appVersion: .*"
          to: "appVersion: ${nextRelease.version}"

  - - "@semantic-release/git"
    - message: "bump app version: ${nextRelease.version}"
      assets:
        - "deployment/helm-chart/Chart.yaml"