tagFormat: v${version}
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - "@google/semantic-release-replace-plugin"
verifyConditions: "@semantic-release/github"
analyzeCommits: 
  - path: "@semantic-release/commit-analyzer"
    preset: conventionalcommits
    releaseRules:
      - type: fix(chart)
        release: patch
      - type: feat(chart)
        release: minor
      - type: feat(chart)!
        release: major
generateNotes:
  - path: "@semantic-release/release-notes-generator"
    preset: conventionalcommits
prepare:
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files: "helm-chart/Chart.yaml"
          allowEmptyPaths: false
          disableGlobs: false
          from: "^version: .*"
          to: "version: ${nextRelease.version}"
  - path: "@semantic-release/git"
    message: "bump chart version: ${nextRelease.version}"
    assets:
      - "helm-chart/Chart.yaml"
publish: "@semantic-release/github"
success: false
fail: false
