name: BumpAppChart
run-name: ${{ github.actor }} pushed app updates
on: 
  push:
    branches:
      - 'main'

jobs:
  push-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            app:
              - 'cmd/**'
              - 'internal/**'
            chart:
              - 'deployment/helm-chart/**'

      - if: steps.changes.outputs.app == 'true'
        steps:
          - name: Semantic Release
            uses: cycjimmy/semantic-release-action@v4
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              extra_plugins: |
                @semantic-release/git
                @semantic-release/exec
                @semantic-release/changelog
                @google/semantic-release-replace-plugin

      - if: ${{ steps.changes.outputs.app == 'true' || steps.changes.outputs.chart == 'true' }}
        steps:
          - name: Semantic Release
            uses: cycjimmy/semantic-release-action@v4
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
            with: 
              extra_plugins: |
                @semantic-release/git
                @semantic-release/exec
                @semantic-release/changelog
                @google/semantic-release-replace-plugin
              working_directory: deployment            