name: PR
run-name: ${{ github.actor }} created PR 🚀
on: [pull_request]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
