name: PushApp
run-name: ${{ github.actor }} pushed app updates
on: 
  push:
    paths-ignore:
      - .github/**
      - deployment/**
jobs:
  push-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/changelog
            @google/semantic-release-replace-plugin